In [1]:
import numpy as np

In [6]:
matrix1 = np.array([[1,2,3], [4,5,6]])
print(matrix1)

[[1 2 3]
 [4 5 6]]


In [9]:

matrix2 = np.array([[2,2,2], [3,4,5]])
print(matrix2)

[[2 2 2]
 [3 4 5]]


In [10]:
# addition of two matrix
print(matrix1 + matrix2)

[[ 3  4  5]
 [ 7  9 11]]


In [11]:
# subtraction of two matrix
print(matrix2 - matrix1)

[[ 1  0 -1]
 [-1 -1 -1]]


In [12]:
# multiplication of two matrix
print(matrix1 * matrix2)

[[ 2  4  6]
 [12 20 30]]


In [15]:
# divide of two matrix
print(matrix1 // matrix2)

[[0 1 1]
 [1 1 1]]


In [18]:
mat1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat2 = np.array([[-1,-2,-3], [4,5,6], [-2,-1,-2]])

print(mat1*mat2)

[[ -1  -4  -9]
 [ 16  25  36]
 [-14  -8 -18]]
