In [1]:
# 1D array

import numpy as np
oneDArray = np.array([1,2,3])

print(oneDArray)
print(oneDArray.ndim)

[1 2 3]
1


In [2]:
# 2D array

import numpy as np
twoDArray = np.array([[1,2,3], [4,5,6]])

print(twoDArray)
print(twoDArray.ndim)

[[1 2 3]
 [4 5 6]]
2


In [4]:
# 3D array

import numpy as np
threeDArray = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,'a']]])

print(threeDArray)
print(threeDArray.ndim)

[[['1' '2' '3']
  ['4' '5' '6']]

 [['7' '8' '9']
  ['10' '11' 'a']]]
3


In [5]:
import numpy as np

twoDArray = np.array([[1,2,3], [4,5,6]])
print(twoDArray[0])
print(twoDArray[1][2])

[1 2 3]
6


In [18]:
import numpy as np

twoDArray = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15]])
print(twoDArray.shape) # matrix size

(5, 3)


In [14]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
for i in arr:
    print(i, end='\t')

1	2	3	4	5	6	7	8	9	10	

In [20]:
for i in twoDArray:
    for j in i:
        print(j, end='\t')
    print()

1	2	3	
4	5	6	
7	8	9	
10	11	12	
13	14	15	
