In [6]:
import numpy as np

In [7]:
zerosArray = np.zeros(10)
print(zerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
onesArray = np.ones(10)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
onesArray = onesArray.astype(int)
print(onesArray)

[1 1 1 1 1 1 1 1 1 1]


In [12]:
preFilledArray = np.full(10, 5)
print(preFilledArray)

[5 5 5 5 5 5 5 5 5 5]


In [13]:
# adding a Scalar
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix + 2)

[[3 4 5]
 [6 7 8]]


In [14]:
# subtraction in numpy array
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix - 2)

[[-1  0  1]
 [ 2  3  4]]


In [17]:
# multication in numpy array
print(matrix * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [18]:
# divide in numpy array)
print(matrix / 2)
print(matrix // 2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[0 1 1]
 [2 2 3]]


In [19]:
# power in numpy array
print(matrix ** 2)

[[ 1  4  9]
 [16 25 36]]


In [20]:
# transpose of array(matrix)
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]
